name: Deploy da aplicação

on: 
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: contains( github.event.label.name, 'deploy dev')
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.GH_PACKAGES_TOKEN }}"
          target_url: http://my-app-url.com
          environment: production
          pr: true
          pr_id	: ${GITHUB_EVENT_PATH}
        
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'demogithubday'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: 'ghcr.io/julioarruda/demogithubday:latest'
          
      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ secrets.GH_PACKAGES_TOKEN }}"
          target_url: http://my-app-url.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          pr: true
          pr_id	: ${GITHUB_EVENT_PATH}

      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ secrets.GH_PACKAGES_TOKEN }}"
          target_url: http://my-app-url.com
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          pr: true
          pr_id	: ${GITHUB_EVENT_PATH}
