name: Build Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.GH_PACKAGES_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build the Docker image
        run: |
         docker build . --file Dockerfile --tag ghcr.io/julioarruda/demogithubday:${{ github.sha }}
         docker tag ghcr.io/julioarruda/demogithubday:${{ github.sha }} ghcr.io/julioarruda/demogithubday:latest

      - name: Docker Push
        run: |
         docker push ghcr.io/julioarruda/demogithubday:${{ github.sha }}
         docker push ghcr.io/julioarruda/demogithubday:latest
       
